name: Push to branch

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  push:
    uses: cloudbeds/workflows/.github/workflows/npm-test-build.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
